import { useQuery } from '@tanstack/react-query'
import { ArrowDownLeft,ArrowUpRight,Banknote,ChevronRight,Landmark,RefreshCw } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../features/auth/auth-context'
import { listCashSessions } from '../../features/cash/cash.api'
import type { CashSession } from '../../features/cash/cash.types'
const money=(value?:string|null)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value??0));const time=(value:string)=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(value))
export function CashOverviewPage(){const{session}=useAuth();const establishmentId=session?.establishments[0]?.id;const query=useQuery({queryKey:['cash-sessions','open',establishmentId],queryFn:()=>listCashSessions(establishmentId!,'OPEN'),enabled:Boolean(establishmentId)});const sessions=query.data??[];const balance=sessions.reduce((sum,item)=>sum+Number(item.expectedAmount??item.openingAmount),0);return <section className="cash-content"><div className="cash-metrics"><article><span className="cash-metric-icon green"><Landmark size={19}/></span><div><small>Caixas abertos</small><strong>{sessions.length}</strong></div></article><article><span className="cash-metric-icon blue"><Banknote size={19}/></span><div><small>Saldo esperado</small><strong>{money(String(balance))}</strong></div></article><article><span className="cash-metric-icon amber"><ArrowUpRight size={19}/></span><div><small>Entradas da sessão</small><strong>{money(String(totalBySign(sessions,true)))}</strong></div></article><article><span className="cash-metric-icon coral"><ArrowDownLeft size={19}/></span><div><small>Saídas da sessão</small><strong>{money(String(Math.abs(totalBySign(sessions,false))))}</strong></div></article></div><div className="cash-panel"><header><div><span className="panel-kicker">Em operação</span><h2>Sessões abertas</h2></div><button onClick={()=>void query.refetch()}><RefreshCw size={15} className={query.isFetching?'spin':''}/> Atualizar</button></header>{query.isLoading?<div className="orders-empty"><RefreshCw className="spin"/><span>Carregando caixas...</span></div>:sessions.length===0?<div className="orders-empty"><Landmark size={31}/><strong>Nenhum caixa aberto</strong><span>Abra uma sessão para começar a operação.</span><Link className="inline-action" to="/caixa/abrir">Abrir um caixa</Link></div>:<div className="cash-session-grid">{sessions.map(item=><Link to={`/caixa/sessoes/${item.id}`} className="cash-session-card" key={item.id}><header><span className="live-dot"/><div><strong>{item.cashRegister.name}</strong><small>{item.cashRegister.code}</small></div><ChevronRight size={17}/></header><dl><div><dt>Aberto às</dt><dd>{time(item.openedAt)}</dd></div><div><dt>Valor inicial</dt><dd>{money(item.openingAmount)}</dd></div><div className="cash-card-total"><dt>Saldo esperado</dt><dd>{money(item.expectedAmount)}</dd></div></dl></Link>)}</div>}</div></section>}
function totalBySign(sessions:CashSession[],positive:boolean){return sessions.flatMap(item=>item.movements??[]).filter(item=>positive?Number(item.amount)>0:Number(item.amount)<0).reduce((sum,item)=>sum+Number(item.amount),0)}
