import { useMutation, useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowDownRight, BarChart3, CalendarDays, CircleDollarSign, Download, PackageX, RefreshCw, ShoppingBag, TrendingUp, UserRound, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../../features/auth/auth-context'
import { createReportExport, getReportExport, getReportOverview } from '../../features/reports/reports.api'
import { ApiError } from '../../lib/api'

const localIso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const initialPeriod = () => { const to = new Date(); const from = new Date(); from.setDate(to.getDate() - 29); return { from: localIso(from), to: localIso(to) } }
const money = (value?: string) => Number(value ?? 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
const number = (value?: string | number) => Number(value ?? 0).toLocaleString('pt-BR', { maximumFractionDigits: 3 })
const paymentNames: Record<string, string> = { CASH: 'Dinheiro', PIX: 'Pix', CREDIT_CARD: 'Crédito à vista', CREDIT_CARD_INSTALLMENT: 'Crédito parcelado', DEBIT_CARD: 'Débito', VOUCHER: 'Voucher', OTHER: 'Outros' }
const movementNames: Record<string, string> = { INITIAL: 'Saldo inicial', PURCHASE: 'Compra', SALE: 'Venda', RETURN: 'Devolução', LOSS: 'Perda', ADJUSTMENT: 'Ajuste', TRANSFER_IN: 'Transferência recebida', TRANSFER_OUT: 'Transferência enviada' }

export function ReportsPage() {
  const { session, currentEstablishment, switchEstablishment } = useAuth()
  const [draft, setDraft] = useState(initialPeriod)
  const [period, setPeriod] = useState(initialPeriod)
  const establishmentId = currentEstablishment?.id ?? ''
  const filters = useMemo(() => ({ establishmentId, ...period, topProductsLimit: 10 }), [establishmentId, period])
  const report = useQuery({ queryKey: ['reports-overview', filters], queryFn: () => getReportOverview(filters), enabled: Boolean(establishmentId) })
  const [jobId, setJobId] = useState('')
  const exportMutation = useMutation({ mutationFn: () => createReportExport(filters), onSuccess: result => setJobId(result.jobId) })
  const exportJob = useQuery({ queryKey: ['report-export', jobId], queryFn: () => getReportExport(jobId), enabled: Boolean(jobId), refetchInterval: query => ['completed', 'failed'].includes(query.state.data?.status ?? '') ? false : 1200 })
  useEffect(() => {
    if (exportJob.data?.status !== 'completed' || !exportJob.data.result) return
    const blob = new Blob([JSON.stringify(exportJob.data.result, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a')
    anchor.href = url; anchor.download = `relatorio-${period.from}-${period.to}.json`; anchor.click(); URL.revokeObjectURL(url)
    setJobId('')
  }, [exportJob.data, period])
  const applyPreset = (days: number) => { const to = new Date(); const from = new Date(); from.setDate(to.getDate() - days + 1); const next = { from: localIso(from), to: localIso(to) }; setDraft(next); setPeriod(next) }
  const data = report.data
  const maxDay = Math.max(...(data?.salesByPeriod.map(item => Number(item.net)) ?? [1]), 1)
  const paymentTotal = data?.salesByPaymentMethod.reduce((sum, item) => sum + Number(item.amount), 0) || 1
  const exporting = exportMutation.isPending || Boolean(jobId)
  return <div className="reports-page page-enter">
    <div className="reports-heading"><div><span className="eyebrow">Inteligência operacional</span><h1>Relatórios</h1><p>Analise vendas, recebimentos e a saúde da operação.</p></div><button className="report-export-button" onClick={() => exportMutation.mutate()} disabled={!establishmentId || exporting}>{exporting ? <RefreshCw size={17} className="spin"/> : <Download size={17}/>} {exporting ? 'Preparando arquivo...' : 'Exportar relatório'}</button></div>
    <section className="report-filter-panel"><div className="report-presets"><span><CalendarDays size={16}/> Período</span>{[7, 30, 90].map(days => <button key={days} onClick={() => applyPreset(days)} className={differenceInDays(period.from, period.to) === days ? 'active' : ''}>{days} dias</button>)}</div><label><span>Unidade</span><select value={establishmentId} onChange={event => switchEstablishment(event.target.value)}>{session?.establishments.map(unit => <option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label><label><span>Data inicial</span><input type="date" value={draft.from} max={draft.to} onChange={event => setDraft({ ...draft, from: event.target.value })}/></label><label><span>Data final</span><input type="date" value={draft.to} min={draft.from} onChange={event => setDraft({ ...draft, to: event.target.value })}/></label><button className="report-apply" onClick={() => setPeriod(draft)} disabled={!draft.from || !draft.to || draft.from > draft.to}><RefreshCw size={16} className={report.isFetching ? 'spin' : ''}/> Aplicar</button></section>
    {report.isError && <div className="notice error-notice"><div><strong>Não foi possível gerar o relatório</strong><span>{report.error instanceof ApiError ? report.error.message : 'Tente novamente em instantes.'}</span></div><button onClick={() => void report.refetch()}>Tentar novamente</button></div>}
    {exportJob.data?.status === 'failed' && <div className="notice error-notice"><div><strong>A exportação falhou</strong><span>{exportJob.data.error ?? 'Solicite o arquivo novamente.'}</span></div><button onClick={() => setJobId('')}>Fechar</button></div>}
    <div className="report-metrics"><ReportMetric label="Vendas líquidas" value={report.isLoading ? '—' : money(data?.sales.net)} note={`Bruto ${money(data?.sales.gross)}`} icon={CircleDollarSign} tone="green"/><ReportMetric label="Vendas concluídas" value={report.isLoading ? '—' : String(data?.sales.count ?? 0)} note={`${data?.salesByPeriod.length ?? 0} dias com movimento`} icon={ShoppingBag} tone="blue"/><ReportMetric label="Ticket médio" value={report.isLoading ? '—' : money(data?.sales.averageTicket)} note="por venda concluída" icon={TrendingUp} tone="violet"/><ReportMetric label="Estornos" value={report.isLoading ? '—' : money(data?.sales.refunded)} note={`${data?.cancellations.count ?? 0} pedidos cancelados`} icon={ArrowDownRight} tone="coral"/></div>
    <div className="reports-main-grid"><section className="report-card sales-evolution"><ReportCardHeader kicker="Desempenho" title="Evolução das vendas" meta={money(data?.sales.net)}/><div className="report-bars">{data?.salesByPeriod.length ? data.salesByPeriod.map(day => <div key={day.date}><span>{money(day.net)}</span><div><i style={{ height: `${Math.max(Number(day.net) / maxDay * 100, 4)}%` }}/></div><small>{new Date(`${day.date}T12:00:00`).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' }).replace('.', '')}</small></div>) : <ReportEmpty text="Nenhuma venda no período."/>}</div></section><section className="report-card"><ReportCardHeader kicker="Recebimentos" title="Formas de pagamento"/><div className="report-payment-list">{data?.salesByPaymentMethod.length ? data.salesByPaymentMethod.map((item, index) => { const share = Number(item.amount) / paymentTotal * 100; return <div key={item.method}><span className={`report-color color-${index % 5}`}/><p><strong>{paymentNames[item.method] ?? item.method}</strong><small>{item.count} transações</small></p><div><strong>{money(item.amount)}</strong><small>{share.toFixed(1)}%</small></div><i><b style={{ width: `${share}%` }}/></i></div> }) : <ReportEmpty text="Sem recebimentos."/>}</div></section></div>
    <div className="reports-secondary-grid"><section className="report-card"><ReportCardHeader kicker="Ranking" title="Produtos mais vendidos"/><div className="report-ranking">{data?.topProducts.length ? data.topProducts.map((product, index) => <article key={`${product.productId}-${product.name}`}><em>{String(index + 1).padStart(2, '0')}</em><span><ShoppingBag size={16}/></span><p><strong>{product.name}</strong><small>{number(product.quantity)} unidades</small></p><b>{money(product.total)}</b></article>) : <ReportEmpty text="Sem produtos vendidos."/>}</div></section><section className="report-card"><ReportCardHeader kicker="Equipe" title="Vendas por operador"/><div className="report-ranking operators">{data?.salesByOperator.length ? data.salesByOperator.map((operator, index) => <article key={operator.userId}><em>{String(index + 1).padStart(2, '0')}</em><span><UserRound size={16}/></span><p><strong>{operator.name}</strong><small>{operator.count} vendas</small></p><b>{money(operator.total)}</b></article>) : <ReportEmpty text="Sem vendas por operador."/>}</div></section></div>
    <section className="report-operations"><header><div><span className="eyebrow">Controle da operação</span><h2>Indicadores operacionais</h2></div></header><div><OperationCard icon={AlertTriangle} title="Cancelamentos" value={String(data?.cancellations.count ?? 0)} note={money(data?.cancellations.total)} tone="coral"/><OperationCard icon={WalletCards} title="Diferenças de caixa" value={String(data?.cashDifferences.length ?? 0)} note={money(String(data?.cashDifferences.reduce((sum, item) => sum + Math.abs(Number(item.difference)), 0) ?? 0))} tone="amber"/><OperationCard icon={PackageX} title="Estoque baixo" value={String(data?.lowStock.length ?? 0)} note="itens abaixo do mínimo" tone="violet"/><OperationCard icon={BarChart3} title="Movimentações" value={String(data?.stockMovements.reduce((sum, item) => sum + item.count, 0) ?? 0)} note={`${data?.stockMovements.length ?? 0} tipos no período`} tone="blue"/></div></section>
    <div className="reports-lists-grid"><section className="report-card"><ReportCardHeader kicker="Reposição" title="Itens com estoque baixo"/><div className="report-alert-list">{data?.lowStock.length ? data.lowStock.slice(0, 8).map(item => <article key={item.stockItemId}><span><PackageX size={16}/></span><p><strong>{item.product}{item.variant ? ` · ${item.variant}` : ''}</strong><small>Mínimo: {number(item.minimumQuantity)}</small></p><b>{number(item.quantity)}</b></article>) : <ReportEmpty text="Nenhum item abaixo do mínimo."/>}</div></section><section className="report-card"><ReportCardHeader kicker="Inventário" title="Movimentações de estoque"/><div className="report-movement-list">{data?.stockMovements.length ? data.stockMovements.map(item => <article key={item.type}><p><strong>{movementNames[item.type] ?? item.type}</strong><small>{item.count} lançamentos</small></p><b>{number(item.quantity)}</b></article>) : <ReportEmpty text="Sem movimentações no período."/>}</div></section></div>
  </div>
}

const differenceInDays = (from: string, to: string) => Math.round((Date.parse(`${to}T12:00:00`) - Date.parse(`${from}T12:00:00`)) / 86_400_000) + 1
function ReportMetric({ label, value, note, icon: Icon, tone }: { label: string; value: string; note: string; icon: typeof CircleDollarSign; tone: string }) { return <article><span className={tone}><Icon size={20}/></span><p><small>{label}</small><strong>{value}</strong><em>{note}</em></p></article> }
function ReportCardHeader({ kicker, title, meta }: { kicker: string; title: string; meta?: string }) { return <header className="report-card-header"><div><span>{kicker}</span><h2>{title}</h2></div>{meta && <strong>{meta}</strong>}</header> }
function ReportEmpty({ text }: { text: string }) { return <div className="report-empty"><BarChart3 size={22}/><span>{text}</span></div> }
function OperationCard({ icon: Icon, title, value, note, tone }: { icon: typeof AlertTriangle; title: string; value: string; note: string; tone: string }) { return <article><span className={tone}><Icon size={19}/></span><p><small>{title}</small><strong>{value}</strong><em>{note}</em></p></article> }
