import { useQuery } from '@tanstack/react-query'
import { ArrowDownLeft,ArrowUpRight,History,RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../../features/auth/auth-context'
import { listStockMovements } from '../../features/stock/stock.api'
import { movementTypeLabels,type StockMovementType } from '../../features/stock/stock.types'
import { listProducts } from '../../features/catalog/catalog.api'
const quantity=(value:string)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3,signDisplay:'always'}).format(Number(value))
export function StockMovementsPage(){const{currentEstablishment}=useAuth();const id=currentEstablishment?.id;const[type,setType]=useState<StockMovementType|''>('');const query=useQuery({queryKey:['stock-movements',id,type],queryFn:()=>listStockMovements({establishmentId:id!,type:type||undefined}),enabled:Boolean(id)});const products=useQuery({queryKey:['products','stock-movements'],queryFn:()=>listProducts()});const productName=(productId:string)=>products.data?.find(item=>item.id===productId)?.name??'Produto';return <section className="stock-panel"><header><div><span className="panel-kicker">Auditoria operacional</span><h2>Histórico de movimentações</h2></div><select value={type} onChange={event=>setType(event.target.value as StockMovementType|'')}><option value="">Todos os tipos</option>{Object.entries(movementTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></header><div className="movement-timeline">{(query.data??[]).map(item=>{const incoming=Number(item.quantity)>=0;return <article key={item.id}><span className={incoming?'in':'out'}>{incoming?<ArrowUpRight size={18}/>:<ArrowDownLeft size={18}/>}</span><div><strong>{productName(item.productId)}</strong><small>{movementTypeLabels[item.type]}{item.reason?` · ${item.reason}`:''}</small></div><time>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.createdAt))}</time><b className={incoming?'positive':'negative'}>{quantity(item.quantity)}</b><em>{item.balanceBefore} → {item.balanceAfter}</em></article>})}</div>{query.isLoading&&<div className="orders-empty"><RefreshCw className="spin"/></div>}{!query.isLoading&&!query.data?.length&&<div className="orders-empty"><History size={31}/><strong>Nenhuma movimentação encontrada</strong></div>}</section>}
