import { useQuery } from '@tanstack/react-query'
import { ChevronRight,ClipboardList,RefreshCw,Search } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../features/auth/auth-context'
import { listOrders } from '../../features/orders/orders.api'
import { orderStatus,orderType,type OrderStatus,type OrderType } from '../../features/orders/orders.types'
import { ApiError } from '../../lib/api'
const money=(value:string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));const dateTime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))
export function OrdersPage(){const{session}=useAuth();const establishmentId=session?.establishments[0]?.id;const[status,setStatus]=useState<OrderStatus|''>('');const[type,setType]=useState<OrderType|''>('');const[search,setSearch]=useState('');const query=useQuery({queryKey:['orders',establishmentId,status,type],queryFn:()=>listOrders({establishmentId:establishmentId!,status:status||undefined,type:type||undefined}),enabled:Boolean(establishmentId)});const normalized=search.trim().toLowerCase();const orders=(query.data??[]).filter(order=>!normalized||String(order.sequence).includes(normalized)||String(order.customer?.name??'').toLowerCase().includes(normalized));return <section className="orders-content"><div className="orders-filters"><label className="order-search"><Search size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar por número ou cliente"/></label><select value={status} onChange={event=>setStatus(event.target.value as OrderStatus|'')}><option value="">Todos os status</option>{Object.entries(orderStatus).map(([value,item])=><option key={value} value={value}>{item.label}</option>)}</select><select value={type} onChange={event=>setType(event.target.value as OrderType|'')}><option value="">Todos os canais</option>{Object.entries(orderType).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button onClick={()=>void query.refetch()}><RefreshCw size={17} className={query.isFetching?'spin':''}/></button></div>{query.error&&<div className="notice error-notice"><div><strong>Não foi possível carregar os pedidos</strong><span>{query.error instanceof ApiError?query.error.message:'Tente novamente em instantes.'}</span></div><button onClick={()=>void query.refetch()}>Tentar novamente</button></div>}<div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Pedido</th><th>Canal</th><th>Cliente</th><th>Itens</th><th>Data</th><th>Total</th><th>Status</th><th/></tr></thead><tbody>{orders.map(order=>{const info=orderStatus[order.status];return <tr key={order.id}><td><strong>#{String(order.sequence).padStart(4,'0')}</strong></td><td>{orderType[order.type]}</td><td>{String(order.customer?.name??'Não informado')}</td><td>{order.items.length}</td><td>{dateTime(order.createdAt)}</td><td><strong>{money(order.total)}</strong></td><td><span className={`order-status ${info.className}`}>{info.label}</span></td><td><Link to={`/pedidos/${order.id}`}><ChevronRight size={18}/></Link></td></tr>})}</tbody></table>{!query.isLoading&&orders.length===0&&<div className="orders-empty"><ClipboardList size={32}/><strong>Nenhum pedido encontrado</strong><span>Ajuste os filtros ou crie um novo pedido.</span></div>}{query.isLoading&&<div className="orders-empty"><RefreshCw className="spin" size={28}/><span>Carregando pedidos...</span></div>}</div></section>}
