import { useQuery } from '@tanstack/react-query'
import { ArrowRight, Building2, CircleCheck, CirclePause, Plus, RefreshCw, ShieldAlert, Store } from 'lucide-react'
import { Link } from 'react-router-dom'
import { listAdminCompanies } from '../../features/admin/admin.api'

export function AdminDashboardPage() {
  const companies = useQuery({ queryKey: ['admin-companies'], queryFn: () => listAdminCompanies() })
  const data = companies.data ?? []
  return <div className="admin-page page-enter"><div className="admin-page-heading"><div><span className="eyebrow">NexPDV Platform</span><h1>Visão geral</h1><p>Acompanhe e gerencie todas as operações da plataforma.</p></div><Link className="admin-primary" to="/admin/empresas/nova"><Plus size={18}/> Nova empresa</Link></div><div className="admin-metrics"><article><span className="violet"><Building2 size={21}/></span><div><small>Empresas cadastradas</small><strong>{data.length}</strong></div></article><article><span className="green"><CircleCheck size={21}/></span><div><small>Empresas ativas</small><strong>{data.filter(item => item.status === 'ACTIVE').length}</strong></div></article><article><span className="amber"><CirclePause size={21}/></span><div><small>Inativas ou suspensas</small><strong>{data.filter(item => item.status !== 'ACTIVE').length}</strong></div></article><article><span className="blue"><Store size={21}/></span><div><small>Moeda predominante</small><strong>{data[0]?.currency ?? 'BRL'}</strong></div></article></div><section className="admin-panel"><header><div><span className="panel-kicker">Cadastros recentes</span><h2>Últimas empresas</h2></div><Link to="/admin/empresas">Ver todas <ArrowRight size={14}/></Link></header><div className="admin-company-list">{data.slice(0, 6).map(company => <Link to={`/admin/empresas/${company.id}`} key={company.id}><span>{company.tradeName.slice(0, 2).toUpperCase()}</span><div><strong>{company.tradeName}</strong><small>{company.legalName}</small></div><i className={company.status.toLowerCase()}>{company.status === 'ACTIVE' ? 'Ativa' : company.status === 'SUSPENDED' ? 'Suspensa' : 'Inativa'}</i><ArrowRight size={16}/></Link>)}</div>{companies.isLoading && <div className="admin-empty"><RefreshCw className="spin"/></div>}{companies.isError && <div className="admin-empty"><ShieldAlert size={28}/><strong>Não foi possível carregar o ambiente</strong><span>Tente novamente em alguns instantes.</span></div>}{!companies.isLoading && !companies.isError && !data.length && <div className="admin-empty"><Building2 size={28}/><strong>Nenhuma empresa cadastrada</strong><span>Crie a primeira empresa da plataforma.</span></div>}</section></div>
}
